stages:
    - build
    - lint
    - test

services:
  - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  image: docker
  script:
    - docker buildx build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE


lint check driver and utils 1/3:
  stage: lint
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker run $CI_REGISTRY_IMAGE prospector --profile prospector.yaml driver.py
    - docker run $CI_REGISTRY_IMAGE prospector --profile prospector.yaml utils.py

lint check tasks 2/3:
  stage: lint
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker run $CI_REGISTRY_IMAGE prospector --profile prospector.yaml task_solver

lint check tests 3/3:
  stage: lint
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker run $CI_REGISTRY_IMAGE prospector --profile prospector.yaml tests


test:
  stage: test
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker run $CI_REGISTRY_IMAGE pytest tests
